
ALTER TABLE public.promotions ADD COLUMN IF NOT EXISTS timer_minutos INTEGER DEFAULT NULL;
ALTER TABLE public.promotions ADD COLUMN IF NOT EXISTS cotas_dobro BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE public.promotions ADD COLUMN IF NOT EXISTS ativado_em TIMESTAMP WITH TIME ZONE DEFAULT NULL;
